### PR TITLE
Pascal66 // rebase target: elliot_waves

### PR DESCRIPTION
**Pull request by Pascal66**

### CODE REVIEW

**Comment by kuzetsa** [comment]
This pull request is huge...

Any chance you'd be up to discussing it?

**Comment by kuzetsa** [comment]
A rebase / proper merge can be done later.

For now, I'm just going to stick it in a new branch.

In the future, please try to do better than:

```
No description provided.
```

(_next time please explain what you're trying to do or why there are so many commits._

**Comment by kuzetsa** [comment]
I haven't tested this...

It's merged to the newly created branch

**UNTESTED / download and use if you want though:**

https://github.com/kuzetsa/gekko/releases/tag/Pascal66%402016_Aug_26

**Comment by Pascal66** [comment]
Sorry, i think i've made a mistake. I removed this branch

**Comment by kuzetsa** [comment]
@Pascal66 Either way is fine.

It can be dealt with at a later time if you decide you want to do anything with it.

Not sure if/when I might have a look at the code...

I had a bad experience in 2014 after counterparty risk (_an exchange / platform for mining hashrate_)

They were using my mining hardware but then one day stopped paying me for leasing out usage of my hardware & electricity. It was very upsetting, and I've barely touched bitcoin since then. (_including my work on gekko abruptly ending at around the same time._)

... Unrelatedly -- That particular event was also around the time cex.io stopped selling GHS actually (_which was the main thing I was using gekko for managing_)

**Pull request merged**
